# Adapted from FPComplete's Haskell Travis Config:
#   https://www.fpcomplete.com/blog/2016/02/updated-haskell-travis-config

sudo: false

# Choose a lightweight base image; we provide our own tools.
language: c

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'


install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --no-terminal -j1 --install-ghc build --only-dependencies

script:
  - stack --no-terminal -j1 build

notifications:
  email: true

before_deploy:
  - mkdir bundle
  - cp `stack path --dist-dir`/build/pursuit/pursuit bundle/
  - cp LICENSE bundle/
  - tar czf pursuit.tar.gz -C bundle/ .

deploy:
  provider: releases
  api_key: $RELEASE_KEY
  file: pursuit.tar.gz
  skip_cleanup: true
  on:
    tags: true
